Repository SpartaCoding-iOS5/LuckVii, pull requests merged in 2024-12, with the labels that each got.

#6 chore: 프로젝트 초기 설정 (main -> develop)
  LuckVii/LuckVii/Modal/Modal.swift
  LuckVii/LuckVii/Utility/Font.swift
  LuckVii/LuckVii/View/View.swift
  README.md
Labels: chore

#10 [#8] feat LoginView UI
  LuckVii/LuckVii/View/LoginView.swift
Labels: feat

#13 [#9] feat SearchView UI feature
  LuckVii/LuckVii/View/SearchView.swift
  LuckVii/LuckVii/View/SearchViewCell.swift
Labels: feat

#17 [#11] Feat signup view UI
  LuckVii/LuckVii/View/LoginView.swift
  LuckVii/LuckVii/View/SignUpView.swift
Labels: feat

#22 [#21] Feat NetworkService 구현
  LuckVii/LuckVii/Service/ImageService/ImageManager.swift
  LuckVii/LuckVii/Service/MovieDataService/MovieData.swift
  LuckVii/LuckVii/Service/MovieDataService/MovieManager+Extension.swift
  LuckVii/LuckVii/Service/MovieDataService/MovieManager.swift
  LuckVii/LuckVii/Service/NetworkError.swift
Labels: feat

#24 [#12] Feat PaymentView 구현
  LuckVii/LuckVii/Controller/PaymentViewController.swift
  LuckVii/LuckVii/Model/PriceFormatModel.swift
  LuckVii/LuckVii/View/PaymentView/PaymentView.swift
Labels: feat

#25 [#18] Feat LoginViewController 구현
  LuckVii/LuckVii/Controller/LoginViewController.swift
  LuckVii/LuckVii/View/LoginView.swift
Labels: feat

#29 [#15] moviedetailview 그라데이션 작업 추가
  LuckVii/LuckVii/View/MovieDetailView.swift
Labels: feat

#37 [#23] feat 검색 화면 api 연동, 검색 화면과 상세 화면 연결
  LuckVii/LuckVii/Controller/MovieDetailViewController.swift
  LuckVii/LuckVii/Controller/SearchViewController.swift
  LuckVii/LuckVii/Service/MovieDataService/MovieData.swift
  LuckVii/LuckVii/View/MovieDetailView.swift
  LuckVii/LuckVii/View/SearchView/SearchViewCell.swift
Labels: feat

#38 [#38] Feat AgreementTermsView 구현
  LuckVii/LuckVii/View/PaymentView/AgreementTermsView.swift
Labels: feat

#39 [#28] Feat SignUpViewController 구현
  LuckVii/LuckVii/Controller/SignUpViewController.swift
  LuckVii/LuckVii/Model/UserInfo.swift
  LuckVii/LuckVii/View/SignUpView.swift
  LuckVii/UserInfo+CoreDataClass.swift
  LuckVii/UserInfo+CoreDataProperties.swift
Labels: feat

#41 [#33] selectdateview/date 뷰 구현
  LuckVii/LuckVii/Controller/SelectDateViewController.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDescriptionView.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDetailView.swift
  LuckVii/LuckVii/View/SelectDateView.swift
Labels: feat

#44 [#19] Feat MypageView UI 구현
  LuckVii/LuckVii/View/MypageView/MovieReservationCell.swift
  LuckVii/LuckVii/View/MypageView/MyPageView.swift
Labels: feat

#45 [#43] Feat MyPageView 및 TableViewCell -> MyPageViewController 연결
  LuckVii/LuckVii/Controller/MyPageViewController.swift
Labels: feat

#46 [#27] Feat NetworkService
  LuckVii/LuckVii.xcodeproj/project.pbxproj
  LuckVii/LuckVii/Controller/SearchViewController.swift
  LuckVii/LuckVii/Service/DecodableData/DetailData.swift
  LuckVii/LuckVii/Service/DecodableData/MovieData.swift
  LuckVii/LuckVii/Service/DecodableData/VideoData.swift
  LuckVii/LuckVii/Service/Manager/ImageManager.swift
  LuckVii/LuckVii/Service/Manager/NetworkManager+Extension.swift
  LuckVii/LuckVii/Service/Manager/NetworkManager.swift
  LuckVii/LuckVii/Service/MovieDataService/MovieManager+Extension.swift
Labels: feat

#50 [#42] Feat moviedetailviewcontroller api 연결
  LuckVii/LuckVii/Controller/MovieDetailViewController.swift
  LuckVii/LuckVii/Controller/SelectDateViewController.swift
  LuckVii/LuckVii/Service/DecodableData/DetailData.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDescriptionView.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDetailView.swift
  LuckVii/LuckVii/View/SearchView/SearchView.swift
Labels: feat

#52 [#36] Feat ArgreementTermsViewController 모달 연결
  LuckVii/LuckVii/Controller/AgreementTermsViewController.swift
  LuckVii/LuckVii/Controller/PaymentViewController.swift
  LuckVii/LuckVii/View/PaymentView/AgreementTermsView.swift
  LuckVii/LuckVii/View/PaymentView/PaymentView.swift
Labels: feat

#54 [#31] feat 뽑기 결과 화면 View 구현
  LuckVii/LuckVii/Controller/ViewController.swift
  LuckVii/LuckVii/View/PaymentView/PaymentResultView.swift
Labels: feat

#55 51 add error case
  LuckVii/LuckVii/Controller/MovieDetailViewController.swift
  LuckVii/LuckVii/Error/AppError.swift
  LuckVii/LuckVii/Service/DecodableData/DetailData.swift
  LuckVii/LuckVii/Service/DecodableData/VideoData.swift
  LuckVii/LuckVii/Service/Manager/ImageManager.swift
  LuckVii/LuckVii/Service/Manager/NetworkManager.swift
  LuckVii/LuckVii/Service/NetworkError.swift
Labels: chore, feat

#57 [#35] Feat SelectDateVC PaymentVC 데이터 연결
  LuckVii/LuckVii/Controller/MovieDetailViewController.swift
  LuckVii/LuckVii/Controller/PaymentViewController.swift
  LuckVii/LuckVii/Controller/SelectDateViewController.swift
  LuckVii/LuckVii/View/PaymentView/PaymentView.swift
  LuckVii/LuckVii/View/SelectDateView.swift
Labels: feat

#59 [#56] Feat moviedetailviewcontrollerfix
  LuckVii/LuckVii/Controller/MovieDetailViewController.swift
  LuckVii/LuckVii/Service/DecodableData/DetailData.swift
  LuckVii/LuckVii/Service/DecodableData/VideoData.swift
Labels: feat

#60 [#40] Feat UserInfo CoreData
  LuckVii/LuckVii.xcodeproj/project.pbxproj
  LuckVii/LuckVii/Controller/SignUpViewController.swift
  LuckVii/LuckVii/LuckVii.xcdatamodeld/LuckVii.xcdatamodel/contents
  LuckVii/LuckVii/Model/UserDataManager.swift
  LuckVii/LuckVii/Model/UserInfo.swift
  LuckVii/LuckVii/Model/UserInfoData.swift
  LuckVii/LuckVii/View/LoginView.swift
  LuckVii/LuckVii/View/SignUpView.swift
  LuckVii/UserInfo+CoreDataClass.swift
Labels: feat

#63 ✨ [Feat]: paymentResultViewController 구현
  LuckVii/LuckVii/Controller/PaymentResultViewController.swift
  LuckVii/LuckVii/View/PaymentView/AgreementTermsView.swift
  LuckVii/LuckVii/View/PaymentView/PaymentResultView.swift
Labels: feat

#64 [#58] Feat SelectDateView 시간 선택 구현 및 데이터 연결
  LuckVii/LuckVii/Controller/SelectDateViewController.swift
  LuckVii/LuckVii/View/PaymentView/PaymentView.swift
  LuckVii/LuckVii/View/SelectDateView.swift
  LuckVii/LuckVii/View/TimeCollectionViewCell.swift
Labels: feat

#66 [#62] refac error case
  LuckVii/LuckVii/Controller/MovieDetailViewController.swift
  LuckVii/LuckVii/Controller/SelectDateViewController.swift
  LuckVii/LuckVii/Error/AppError.swift
  LuckVii/LuckVii/Service/DecodableData/DetailData.swift
Labels: chore

#67 [#65]: SearchView의 UICollectionView 셀 간격 조정
  LuckVii/LuckVii/Controller/SearchViewController.swift
  LuckVii/LuckVii/View/SearchView/SearchView.swift
Labels: chore

#71 [#61] Login 기능 구현
  LuckVii/LuckVii/Controller/LoginViewController.swift
  LuckVii/LuckVii/Controller/SignUpViewController.swift
  LuckVii/LuckVii/Model/UserDataManager.swift
  LuckVii/LuckVii/SceneDelegate.swift
  LuckVii/LuckVii/View/LoginView.swift
Labels: feat

#72 [#68] Feat main view
  LuckVii/LuckVii/Controller/Login/LoginViewController.swift
  LuckVii/LuckVii/Controller/Login/SignUpViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/Category/CategoryViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/MainTabBarController.swift
  LuckVii/LuckVii/Controller/MainTabs/Mypage/MyPageViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/Search/SearchViewController.swift
  LuckVii/LuckVii/Controller/Movie Detail/MovieDetailViewController.swift
  LuckVii/LuckVii/Controller/Payment/AgreementTermsViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentResultViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentViewController.swift
  LuckVii/LuckVii/Controller/Payment/SelectDateViewController.swift
  LuckVii/LuckVii/Controller/ViewController.swift
  LuckVii/LuckVii/SceneDelegate.swift
  LuckVii/LuckVii/Service/Manager/NetworkManager+Extension.swift
  LuckVii/LuckVii/View/CategoryView/MovieCollectionView.swift
  LuckVii/LuckVii/View/CategoryView/MoviePosterCell.swift
Labels: chore, feat

#75 [#70] Feat ResultPaymentVC 데이터 연결
  LuckVii/LuckVii/Controller/Payment/PaymentResultViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentViewController.swift
  LuckVii/LuckVii/Controller/Payment/SelectDateViewController.swift
  LuckVii/LuckVii/SceneDelegate.swift
  LuckVii/LuckVii/View/PaymentView/PaymentResultView.swift
  LuckVii/LuckVii/View/PaymentView/PaymentView.swift
Labels: feat

#78 [#74] Feat 검색 화면에서 Segemented Control 기능 구현
  LuckVii/LuckVii/Controller/MainTabs/Search/SearchViewController.swift
  LuckVii/LuckVii/View/SearchView/SearchView.swift
Labels: feat

#77 [#73] Feat moviedetailviewRefactor
  LuckVii/LuckVii/Controller/Movie Detail/MovieDetailViewController.swift
  LuckVii/LuckVii/SceneDelegate.swift
  LuckVii/LuckVii/Service/DecodableData/DetailData.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDescriptionView.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDetailView.swift
Labels: feat

#79 [#47] Feat 고객 예매 상세페이지 뷰 구현 UI 구현
  LuckVii/LuckVii/View/ReservationDetailView/ReservationDetailView.swift
Labels: feat

#80 [#48] Feat 고객 예매 상세페이지 뷰 컨트롤러 구현
  LuckVii/LuckVii/Controller/MainTabs/RvPage/ReservationDetailViewController.swift
Labels: feat

#84 [#68] Feat main view
  LuckVii/LuckVii/Controller/MainTabs/Category/CategoryViewController+Extension.swift
  LuckVii/LuckVii/Controller/MainTabs/Category/CategoryViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/MainTabBarController.swift
  LuckVii/LuckVii/Controller/MainTabs/Search/SearchViewController.swift
  LuckVii/LuckVii/Model/MovieDataSource.swift
  LuckVii/LuckVii/SceneDelegate.swift
  LuckVii/LuckVii/Service/Manager/NetworkManager+Extension.swift
  LuckVii/LuckVii/View/CategoryView/MovieCollectionView.swift
  LuckVii/LuckVii/View/CategoryView/MoviePosterCell.swift
Labels: chore, feat

#86 [#86] Refac 회원가입 뷰 - 닉네임 추가 및 스크롤뷰 수정
  LuckVii/LuckVii/View/Login/LoginView.swift
  LuckVii/LuckVii/View/Login/SignUpView.swift
Labels: Refactor

#88 [#87] Feat SignupViewController, CoreData 닉네임 추가
  LuckVii/LuckVii/Controller/Login/SignUpViewController.swift
  LuckVii/LuckVii/LuckVii.xcdatamodeld/LuckVii.xcdatamodel/contents
  LuckVii/LuckVii/Model/UserDataManager.swift
  LuckVii/LuckVii/Model/UserInfoData.swift
  LuckVii/LuckVii/View/Login/LoginView.swift
  LuckVii/LuckVii/View/Login/SignUpView.swift
  LuckVii/LuckVii/View/SignUpView.swift
  LuckVii/UserInfo+CoreDataClass.swift
  LuckVii/UserInfo+CoreDataProperties.swift
Labels: feat

#91 [#83] Refactor paymentView UI 개선
  LuckVii/LuckVii/Controller/MainTabs/MainTabBarController.swift
  LuckVii/LuckVii/Controller/Movie Detail/MovieDetailViewController.swift
  LuckVii/LuckVii/Controller/Payment/AgreementTermsViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentResultViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentViewController.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDescriptionView.swift
  LuckVii/LuckVii/View/PaymentView/AgreementTermsView.swift
  LuckVii/LuckVii/View/PaymentView/PaymentView.swift
  LuckVii/LuckVii/View/SelectDateView.swift
Labels: feat

#85 [#68] Chore change upcoming movie page
  LuckVii/LuckVii/Controller/MainTabs/Category/CategoryViewController+Extension.swift
  LuckVii/LuckVii/Controller/MainTabs/Category/CategoryViewController.swift
  LuckVii/LuckVii/View/SearchView/SearchView.swift
Labels: chore

#98 [#90] 코어데이터 - 예매내역데이터 저장 및 전달
  LuckVii/LuckVii.xcodeproj/project.pbxproj
  LuckVii/LuckVii/Controller/MainTabs/Mypage/MyPageViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/RvPage/ReservationDetailViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentResultViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentViewController.swift
  LuckVii/LuckVii/LuckVii.xcdatamodeld/LuckVii.xcdatamodel/contents
  LuckVii/LuckVii/Model/ReservationInfoData.swift
  LuckVii/LuckVii/Model/TicketInfoData.swift
  LuckVii/LuckVii/Model/UserDataManager.swift
  LuckVii/LuckVii/View/MypageView/MovieReservationCell.swift
  LuckVii/LuckVii/View/ReservationDetailView/ReservationDetailView.swift
  LuckVii/ReservationInfo+CoreDataClass.swift
  LuckVii/ReservationInfo+CoreDataProperties.swift
  LuckVii/ReservationInfo.swift
  LuckVii/TicketInfo+CoreDataClass.swift
  LuckVii/TicketInfo+CoreDataProperties.swift
  LuckVii/TicketInfo.swift
  LuckVii/UserInfo+CoreDataProperties.swift
  LuckVii/UserInfo.swift
Labels: feat

#96 [#94] 영화 목록뷰, 검색뷰 UI 약간 수정
  LuckVii/LuckVii/Assets.xcassets/Color1.colorset/Contents.json
  LuckVii/LuckVii/Assets.xcassets/Color2.colorset/Contents.json
  LuckVii/LuckVii/Assets.xcassets/Color3.colorset/Contents.json
  LuckVii/LuckVii/Assets.xcassets/Color4.colorset/Contents.json
  LuckVii/LuckVii/Controller/MainTabs/Category/CategoryViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/Search/SearchViewController.swift
  LuckVii/LuckVii/SceneDelegate.swift
  LuckVii/LuckVii/View/CategoryView/MoviePosterCell.swift
  LuckVii/LuckVii/View/Login/LoginView.swift
  LuckVii/LuckVii/View/Login/SignUpView.swift
  LuckVii/LuckVii/View/SearchView/SearchView.swift
  LuckVii/LuckVii/View/SearchView/SearchViewCell.swift
Labels: chore

#97 [#93] feat login view
  LuckVii/LuckVii/Controller/Login/LoginViewController.swift
  LuckVii/LuckVii/Controller/Login/SignUpViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/MainTabBarController.swift
  LuckVii/LuckVii/Controller/Movie Detail/MovieDetailViewController.swift
  LuckVii/LuckVii/Model/LoginManager.swift
  LuckVii/LuckVii/Model/UserDefaults/UserDefaultsManger.swift
Labels: feat

#104 [#102] Refac Swiftlint auto fix
  LuckVii/LuckVii/AppDelegate.swift
  LuckVii/LuckVii/Controller/Login/LoginViewController.swift
  LuckVii/LuckVii/Controller/Login/SignUpViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/Category/CategoryViewController+Extension.swift
  LuckVii/LuckVii/Controller/MainTabs/Category/CategoryViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/MainTabBarController.swift
  LuckVii/LuckVii/Controller/MainTabs/Mypage/MyPageViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/RvPage/ReservationDetailViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/Search/SearchViewController.swift
  LuckVii/LuckVii/Controller/Movie Detail/MovieDetailViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentResultViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentViewController.swift
  LuckVii/LuckVii/Controller/Payment/SelectDateViewController.swift
  LuckVii/LuckVii/Error/AppError.swift
  LuckVii/LuckVii/Model/LoginManager.swift
  LuckVii/LuckVii/Model/UserDataManager.swift
  LuckVii/LuckVii/Model/UserDefaults/UserDefaultsManger.swift
  LuckVii/LuckVii/SceneDelegate.swift
  LuckVii/LuckVii/Service/DecodableData/DetailData.swift
  LuckVii/LuckVii/Service/DecodableData/MovieData.swift
  LuckVii/LuckVii/Service/DecodableData/VideoData.swift
  LuckVii/LuckVii/Service/Manager/ImageManager.swift
  LuckVii/LuckVii/Service/Manager/NetworkManager+Extension.swift
  LuckVii/LuckVii/Service/Manager/NetworkManager.swift
  LuckVii/LuckVii/View/CategoryView/MovieCollectionView.swift
  LuckVii/LuckVii/View/CategoryView/MoviePosterCell.swift
  LuckVii/LuckVii/View/Login/LoginView.swift
  LuckVii/LuckVii/View/Login/SignUpView.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDescriptionView.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDetailView.swift
  LuckVii/LuckVii/View/MypageView/MovieReservationCell.swift
  LuckVii/LuckVii/View/MypageView/MyPageView.swift
  LuckVii/LuckVii/View/PaymentView/AgreementTermsView.swift
  LuckVii/LuckVii/View/PaymentView/BottomButonView.swift
  LuckVii/LuckVii/View/PaymentView/PaymentResultView.swift
  LuckVii/LuckVii/View/PaymentView/PaymentView.swift
  LuckVii/LuckVii/View/ReservationDetailView/ReservationDetailView.swift
  LuckVii/LuckVii/View/SearchView/SearchView.swift
  LuckVii/LuckVii/View/SearchView/SearchViewCell.swift
  LuckVii/LuckVii/View/SelectDateView.swift
  LuckVii/LuckVii/View/TimeCollectionViewCell.swift
  LuckVii/UserInfo+CoreDataProperties.swift
Labels: Refactor

#106 [Feat] CoreData - 예매데이터 연결하기
  LuckVii/LuckVii.xcodeproj/project.pbxproj
  LuckVii/LuckVii/Controller/MainTabs/Mypage/MyPageViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/RvPage/ReservationDetailViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentResultViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentViewController.swift
  LuckVii/LuckVii/LuckVii.xcdatamodeld/LuckVii.xcdatamodel/contents
  LuckVii/LuckVii/Model/MovieReservation.swift
  LuckVii/LuckVii/Model/ReservationInfoData.swift
  LuckVii/LuckVii/Model/TicketInfoData.swift
  LuckVii/LuckVii/Model/UserDataManager.swift
  LuckVii/LuckVii/View/MypageView/MovieReservationCell.swift
  LuckVii/LuckVii/View/ReservationDetailView/ReservationDetailView.swift
  LuckVii/ReservationInfo+CoreDataClass.swift
  LuckVii/ReservationInfo+CoreDataProperties.swift
  LuckVii/ReservationInfo.swift
  LuckVii/TicketInfo+CoreDataClass.swift
  LuckVii/TicketInfo+CoreDataProperties.swift
  LuckVii/TicketInfo.swift
  LuckVii/UserInfo+CoreDataProperties.swift
  LuckVii/UserInfo.swift
Labels: feat

#107 [#102] refac improve code clarity
  LuckVii/LuckVii/Controller/Login/LoginViewController.swift
  LuckVii/LuckVii/Controller/Login/SignUpViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/MainTabBarController.swift
  LuckVii/LuckVii/Controller/MainTabs/Mypage/MyPageViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/RvPage/ReservationDetailViewController.swift
  LuckVii/LuckVii/Controller/MainTabs/Search/SearchViewController.swift
  LuckVii/LuckVii/Controller/Movie Detail/MovieDetailViewController.swift
  LuckVii/LuckVii/Controller/Payment/AgreementTermsViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentResultViewController.swift
  LuckVii/LuckVii/Controller/Payment/PaymentViewController.swift
  LuckVii/LuckVii/Controller/Payment/SelectDateViewController.swift
  LuckVii/LuckVii/Model/Model.swift
  LuckVii/LuckVii/Model/UserDataManager.swift
  LuckVii/LuckVii/Utility/Font.swift
  LuckVii/LuckVii/View/Login/LoginView.swift
  LuckVii/LuckVii/View/Login/SignUpView.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDescriptionView.swift
  LuckVii/LuckVii/View/MovieDetailView/MovieDetailView.swift
  LuckVii/LuckVii/View/MypageView/MovieReservationCell.swift
  LuckVii/LuckVii/View/MypageView/MyPageView.swift
  LuckVii/LuckVii/View/PaymentView/AgreementTermsView.swift
  LuckVii/LuckVii/View/PaymentView/BottomButonView.swift
  LuckVii/LuckVii/View/PaymentView/PaymentResultView.swift
  LuckVii/LuckVii/View/PaymentView/PaymentView.swift
  LuckVii/LuckVii/View/ReservationDetailView/ReservationDetailView.swift
  LuckVii/LuckVii/View/SearchView/SearchView.swift
  LuckVii/LuckVii/View/SearchView/SearchViewCell.swift
  LuckVii/LuckVii/View/SelectDateView.swift
  LuckVii/LuckVii/View/TimeCollectionViewCell.swift
Labels: feat

#118 [#115] MovieDetailView posterImageView Refactor
  LuckVii/LuckVii/View/MovieDetailView/MovieDetailView.swift
Labels: feat

#116 [#114] Save login info
  LuckVii/LuckVii/Controller/Login/LoginViewController.swift
Labels: feat
